### ISSUE TITLE
Pin with 6 or 8 digits

### ISSUE THREAD

**Issue by soko1988** [larsjanssen6/underconstruction#69]
Hi @larsjanssen6 ,
is it possible to configure the amount of digits? 
I think 4 digits is to easy to hack for normal people...

**Comment by larsjanssen6** [comment]
@soko1988 currently not. Maybe I will code it this month.

**Comment by larsjanssen6** [comment]
@soko1988  or send a pull request :)

**Comment by vesper8** [comment]
I would like to see this added.. with at least 6 digits.. 4 is a bit too easy to brute-force

**Comment by larsjanssen6** [comment]
@vesper8 sure reopened issue, will see what I can do.

**Comment by vesper8** [comment]
cool! I had a look at the code and shouldn't be too involving

-add configuration param for setting number of digits
-change validation method in set-code command
-pass config param to under-construction vue component
-use this prop to validate if enough digits have been entered in vue component

think that's it

While you're in there.. maybe you could make it so we can use letters and numbers instead of just numbers, as an option ;)

or maybe only use hexadecimal characters so the "numpad" doesn't get too big
